CREATE TABLE Keskustelualue (
id SERIAL PRIMARY KEY,
Nimi VARCHAR(50)
);

CREATE TABLE Kayttaja (
id SERIAL PRIMARY KEY,
Nimi VARCHAR(30),
Salasana VARCHAR(20)
);

CREATE TABLE Kayttajaryhma (
id SERIAL PRIMARY KEY,
Nimi VARCHAR(30)
);

CREATE TABLE RyhmanKayttajat (
id SERIAL PRIMARY KEY,
Kayttaja INTEGER REFERENCES Kayttaja(id) ON DELETE CASCADE,
Kayttajaryhma INTEGER REFERENCES Kayttajaryhma(id) ON DELETE CASCADE
);

CREATE TABLE Aloitusviesti (
id SERIAL PRIMARY KEY,
Kirjoittaja INTEGER REFERENCES Kayttaja(id) ON DELETE SET NULL,
Keskustelualue INTEGER REFERENCES Keskustelualue(id) ON DELETE CASCADE,
Sisalto VARCHAR(65535),
Otsikko VARCHAR(30),
Paivamaara TIMESTAMP
);

CREATE TABLE Vastine (
id SERIAL PRIMARY KEY,
Kirjoittaja INTEGER REFERENCES Kayttaja(id) ON DELETE SET NULL,
Keskustelualue INTEGER REFERENCES Keskustelualue(id) ON DELETE CASCADE,
Aloitusviesti INTEGER REFERENCES Aloitusviesti(id) ON DELETE CASCADE,
Sisalto VARCHAR(65535),
Paivamaara TIMESTAMP
);


CREATE TABLE ViestinLukeneet (
id SERIAL PRIMARY KEY,
Aloitusviesti INTEGER REFERENCES Aloitusviesti(id) ON DELETE CASCADE,
Kayttaja INTEGER REFERENCES Kayttaja(id) ON DELETE CASCADE
);

CREATE TABLE RyhmanKeskustelualueet (
id SERIAL PRIMARY KEY,
Kayttajaryhma INTEGER REFERENCES Kayttajaryhma(id) ON DELETE CASCADE,
Keskustelualue INTEGER REFERENCES Keskustelualue(id) ON DELETE CASCADE
);